# This is a basic workflow to help you get started with Actions

name: trufflehog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@55b9d48e0de2711b2f6dc70b1c97ac374ccb9dfa # v3.52.1
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          args: --debug
